/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GetRepositoriesByUser: {
            /** Format: int64 */
            id: number;
            node_id: string;
            name: string;
            full_name: string;
            /**
             * Simple User
             * @description A GitHub user.
             */
            owner: {
                name?: string | null;
                email?: string | null;
                login: string;
                /** Format: int64 */
                id: number;
                node_id: string;
                /** Format: uri */
                avatar_url: string;
                gravatar_id: string | null;
                /** Format: uri */
                url: string;
                /** Format: uri */
                html_url: string;
                /** Format: uri */
                followers_url: string;
                following_url: string;
                gists_url: string;
                starred_url: string;
                /** Format: uri */
                subscriptions_url: string;
                /** Format: uri */
                organizations_url: string;
                /** Format: uri */
                repos_url: string;
                events_url: string;
                /** Format: uri */
                received_events_url: string;
                type: string;
                site_admin: boolean;
                starred_at?: string;
                user_view_type?: string;
            };
            private: boolean;
            /** Format: uri */
            html_url: string;
            description: string | null;
            fork: boolean;
            /** Format: uri */
            url: string;
            archive_url: string;
            assignees_url: string;
            blobs_url: string;
            branches_url: string;
            collaborators_url: string;
            comments_url: string;
            commits_url: string;
            compare_url: string;
            contents_url: string;
            /** Format: uri */
            contributors_url: string;
            /** Format: uri */
            deployments_url: string;
            /** Format: uri */
            downloads_url: string;
            /** Format: uri */
            events_url: string;
            /** Format: uri */
            forks_url: string;
            git_commits_url: string;
            git_refs_url: string;
            git_tags_url: string;
            git_url?: string;
            issue_comment_url: string;
            issue_events_url: string;
            issues_url: string;
            keys_url: string;
            labels_url: string;
            /** Format: uri */
            languages_url: string;
            /** Format: uri */
            merges_url: string;
            milestones_url: string;
            notifications_url: string;
            pulls_url: string;
            releases_url: string;
            ssh_url?: string;
            /** Format: uri */
            stargazers_url: string;
            statuses_url: string;
            /** Format: uri */
            subscribers_url: string;
            /** Format: uri */
            subscription_url: string;
            /** Format: uri */
            tags_url: string;
            /** Format: uri */
            teams_url: string;
            trees_url: string;
            clone_url?: string;
            mirror_url?: string | null;
            /** Format: uri */
            hooks_url: string;
            svn_url?: string;
            homepage?: string | null;
            language?: string | null;
            forks_count?: number;
            stargazers_count?: number;
            watchers_count?: number;
            /** @description The size of the repository, in kilobytes. Size is calculated hourly. When a repository is initially created, the size is 0. */
            size?: number;
            default_branch?: string;
            open_issues_count?: number;
            is_template?: boolean;
            topics?: string[];
            has_issues?: boolean;
            has_projects?: boolean;
            has_wiki?: boolean;
            has_pages?: boolean;
            has_discussions?: boolean;
            has_pull_requests?: boolean;
            /**
             * @description The policy controlling who can create pull requests: all or collaborators_only.
             * @enum {string}
             */
            pull_request_creation_policy?: "all" | "collaborators_only";
            archived?: boolean;
            disabled?: boolean;
            visibility?: string;
            /** Format: date-time */
            pushed_at?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            permissions?: {
                admin?: boolean;
                maintain?: boolean;
                push?: boolean;
                triage?: boolean;
                pull?: boolean;
            };
            role_name?: string;
            temp_clone_token?: string;
            delete_branch_on_merge?: boolean;
            subscribers_count?: number;
            network_count?: number;
            /**
             * Code Of Conduct
             * @description Code Of Conduct
             */
            code_of_conduct?: {
                key: string;
                name: string;
                /** Format: uri */
                url: string;
                body?: string;
                /** Format: uri */
                html_url: string | null;
            };
            license?: {
                key?: string;
                name?: string;
                spdx_id?: string;
                url?: string | null;
                node_id?: string;
            } | null;
            forks?: number;
            open_issues?: number;
            watchers?: number;
            allow_forking?: boolean;
            web_commit_signoff_required?: boolean;
            security_and_analysis?: {
                /**
                 * @description Enable or disable GitHub Advanced Security for the repository.
                 *
                 *     For standalone Code Scanning or Secret Protection products, this parameter cannot be used.
                 */
                advanced_security?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                code_security?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                /** @description Enable or disable Dependabot security updates for the repository. */
                dependabot_security_updates?: {
                    /**
                     * @description The enablement status of Dependabot security updates for the repository.
                     * @enum {string}
                     */
                    status?: "enabled" | "disabled";
                };
                secret_scanning?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_push_protection?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_non_provider_patterns?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_ai_detection?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_delegated_alert_dismissal?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_delegated_bypass?: {
                    /** @enum {string} */
                    status?: "enabled" | "disabled";
                };
                secret_scanning_delegated_bypass_options?: {
                    /** @description The bypass reviewers for secret scanning delegated bypass */
                    reviewers?: {
                        /** @description The ID of the team or role selected as a bypass reviewer */
                        reviewer_id: number;
                        /**
                         * @description The type of the bypass reviewer
                         * @enum {string}
                         */
                        reviewer_type: "TEAM" | "ROLE";
                        /**
                         * @description The bypass mode for the reviewer
                         * @default ALWAYS
                         * @enum {string}
                         */
                        mode: "ALWAYS" | "EXEMPT";
                    }[];
                };
            } | null;
            /** @description The custom properties that were defined for the repository. The keys are the custom property names, and the values are the corresponding custom property values. */
            custom_properties?: {
                [key: string]: unknown;
            };
        }[];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
